/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface MyReorder {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyReorderElement extends Components.MyReorder, HTMLStencilElement {}
  var HTMLMyReorderElement: {
    prototype: HTMLMyReorderElement;
    new (): HTMLMyReorderElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-reorder': HTMLMyReorderElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {}
  interface MyReorder extends JSXBase.HTMLAttributes<HTMLMyReorderElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-reorder': MyReorder;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


